name: Release Please
on: 
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: googleapis/release-please-action@v3.7.8
        with:
          token: ${{ secrets.REPO_TOKEN }}
          release-type: "simple"
